export const mockData = [
  {
    id: "111",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameOne",
    firstName: "Adam",
    lastName: "LastName1",
    links: ["link1", "link2", "link3"],
    text: "textSample1",
  },
  {
    id: "112",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameTwo",
    firstName: "Bird",
    lastName: "LastName2",
    links: ["link1", "link2", "link3"],
    text: "textSample2",
  },
  {
    id: "113",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameThree",
    firstName: "Caterine",
    lastName: "LastName3",
    links: ["link1", "link2", "link3"],
    text: "textSample3",
  },
  {
    id: "114",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameThree",
    firstName: "Dan",
    lastName: "LastName4",
    links: ["link1", "link2", "link3"],
    text: "textSample4",
  },
  {
    id: "115",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameFour",
    firstName: "Eric",
    lastName: "LastName5",
    links: ["link1", "link2", "link3"],
    text: "textSample5",
  },
  {
    id: "116",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameFive",
    firstName: "Frankin",
    lastName: "LastName6",
    links: ["link1", "link2", "link3"],
    text: "textSample6",
  },
  {
    id: "117",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Gem",
    lastName: "LastName7",
    links: ["link1", "link2", "link3"],
    text: "textSample7",
  },
  {
    id: "118",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Hana",
    lastName: "LastName8",
    links: ["link1", "link2", "link3"],
    text: "textSample8",
  },
];
