export const mockData = [
  {
    id: "111",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameOne",
    firstName: "Adam",
    lastName: "LastName1",
    tags: ["cpp"],
    links: ["link1", "link2", "link3"],
    text: "textSample1",
  },
  {
    id: "112",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameTwo",
    firstName: "Bird",
    lastName: "LastName2",
    tags: ["cpp"],
    links: ["link1", "link2", "link3"],
    text: "textSample2",
  },
  {
    id: "113",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameThree",
    firstName: "Caterine",
    lastName: "LastName3",
    tags: ["girl"],
    links: ["link1", "link2", "link3"],
    text: "textSample3",
  },
  {
    id: "114",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameThree",
    firstName: "Dan",
    lastName: "LastName4",
    tags: ["girl"],
    links: ["link1", "link2", "link3"],
    text: "textSample4",
  },
  {
    id: "115",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameFour",
    firstName: "Eric",
    lastName: "LastName5",
    tags: ["dog"],
    links: ["link1", "link2", "link3"],
    text: "textSample5",
  },
  {
    id: "116",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameFive",
    firstName: "Frankin",
    lastName: "LastName6",
    tags: ["cat"],
    links: ["link1", "link2", "link3"],
    text: "textSample6",
  },
  {
    id: "117",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Gem",
    lastName: "LastName7",
    tags: ["bird"],
    links: ["link1", "link2", "link3"],
    text: "textSample7",
  },
  {
    id: "118",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Hana",
    lastName: "LastName8",
    tags: ["love"],
    links: ["link1", "link2", "link3"],
    text: "textSample8",
  },
  {
    id: "119",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameFive",
    firstName: "Frankin",
    lastName: "LastName9",
    tags: ["love"],
    links: ["link1", "link2", "link3"],
    text: "textSample9",
  },
  {
    id: "120",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Gem",
    lastName: "LastName10",
    tags: ["dance"],
    links: ["link1", "link2", "link3"],
    text: "textSample10",
  },
  {
    id: "121",
    profileImg: "https://i.imgur.com/MoNWXZl.png",
    userName: "nameSix",
    firstName: "Hana",
    lastName: "LastName11",
    tags: ["cooking"],
    links: ["link1", "link2", "link3"],
    text: "textSample11",
  },
];
